#!/usr/bin/env bash

source "$(dirname $0)/vars"

APP="$1"; PORT="$2"; INT_PORT="$3"; IP="${4:-127.0.0.1}"
hostnames_for_app "$APP"

dokku_log_info1 "Creating avahi alias ${hostname} for ${APP}"
echo "        ${IP}:${PORT} ${INT_PORT}"
avahi-add-alias $hostname

echo "        Restarting avahi-aliases"
/etc/init.d/avahi-daemon restart > /dev/null
