#!/usr/bin/env bash

source "$(dirname $0)/vars"

HOSTNAME=$(< "$DOKKU_ROOT/HOSTNAME")

cat << EOF > /etc/avahi/services/dokku.service
<service-group>
  <name>$HOSTNAME</name>
  <service>
    <type>_ssh._tcp</type>
    <port>22</port>
  </service>
</service-group>
EOF

cat << EOF > /etc/sudoers.d/dokku-avahi-aliases
# dokku-avahi-restart
%dokku ALL=(ALL)NOPASSWD:/sbin/restart avahi-aliases
EOF

chown -R dokku /etc/avahi/aliases.d

/sbin/restart avahi-daemon
