#!/usr/bin/env bash

source "$(dirname $0)/vars"
APP="$1"; PORT="$2"; INT_PORT="$3"; IP="${4:-127.0.0.1}"
hostnames_for_app "$APP"
rm -f /etc/avahi/aliases.d/$hostname >> /dev/null
sudo /sbin/restart avahi-aliases > /dev/null
